# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'JY' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

#  pod 'Alamofire'                , '4.0.1'

  # Pods for JY

  target 'JYTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JYUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
